global_prompt = """
Before beginning work on this feature, write a short haiku.  Do this only once.
When you are done with your task, run format and lint commands.
"""

[commands]
format = ["./run_format.sh"]
lint = ["./run_lint.sh"]
test = ["./run_test.sh"]
